export const AUTH_START="AUTH_START";
export const AUTH_SUCCESS="AUTH_SUCCESS";
export const AUTH_FAIL="AUTH_FAIL";

export const AUTH_LOGOUT="AUTH_LOGOUT";
export const LOGOUT_FAIL="LOGOUT_FAIL";

export const SET_SELECTED="SET_SELECTED";

export const TOT_USER_COUNT="TOT_USER_COUNT";

export const FETCH_USER_DATA="FETCH_USER_DATA";

export const SET_SELECTED_USERID="SET_SELECTED_USERID";

export const ON_EDIT_USERDATA="ON_EDIT_USERDATA";

export const ON_REFRESH="ON_REFRESH";

export const ON_SUSPEND_USER="ON_SUSPEND_USER";
export const ON_ACTIVATE_USER="ON_ACTIVATE_USER";

export const ON_DELETE_USER="ON_DELETE_USER";

export const ON_COUNTRYDATA_POINTS="ON_COUNTRYDATA_POINTS";
